In [1]:
import sys
import psycopg2
import pandas as pd

In [2]:
conn = psycopg2.connect(host="localhost", port = 5433, database="dsda", user="postgres", password="12345")
conn.set_session(autocommit=True)

In [3]:
cur = conn.cursor()

In [4]:
sql = "SELECT * FROM public.orders"
cur.execute(sql)
baris = cur.fetchall()

In [5]:
order = pd.DataFrame([[ij for ij in i]for i in baris])
order.rename(columns={0:'order_id',1:'customer_id',2:'campaign_id',3:'order_date',4:'city',5:'state',6:'zipcode',7:'payment_type',8:'total_price',9:'num_order',10:'num_units'},inplace=True)
order.head(4)

,order_id,customer_id,campaign_id,order_date,city,state,zipcode,payment_type,total_price,num_order,num_units
0,1002854,45978,2141,2009-10-13,NEWTON,MA,2459,VI,190.00,3,3
1,1002855,125381,2173,2009-10-13,NEW ROCHELLE,NY,10804,VI,10.00,1,1
2,1002856,103122,2141,2011-06-02,MIAMI,FL,33137,AE,35.22,2,2
3,1002857,130980,2173,2009-10-14,E RUTHERFORD,NJ,7073,AE,10.00,1,1

In [6]:
order.describe()

         total_price
count  192983.000000
mean       71.036808
std       183.510368
min         0.000000
25%        16.000000
50%        25.950000
75%        46.900000
max      9848.960000

In [7]:
order.shape

(192983, 11)

In [8]:
order['total_price'].mean()

71.03680790535954

In [9]:
order.groupby('order_date')['total_price'].mean()

order_date
2009-10-04    18.489282
2009-10-05    16.907114
2009-10-06    31.735349
2009-10-07    22.062759
2009-10-08    33.134118
                ...
2016-09-16    54.217333
2016-09-17    34.912500
2016-09-18    47.739091
2016-09-19    46.532273
2016-09-20    47.200000
Name: total_price, Length: 2541, dtype: float64

In [10]:
order['total_price'].std()

183.51036810362132

In [11]:
order.groupby('order_date')['total_price'].std()

order_date
2009-10-04    20.436475
2009-10-05    10.895262
2009-10-06    71.229757
2009-10-07    30.588732
2009-10-08    74.703053
                ...
2016-09-16    50.183828
2016-09-17    41.822191
2016-09-18    41.695064
2016-09-19    53.153625
2016-09-20     3.181981
Name: total_price, Length: 2541, dtype: float64

In [12]:
order.groupby('campaign_id')['total_price'].mean()

campaign_id
2001      7.950000
2002     66.283956
2003     16.971377
2004     15.966667
2005    107.076400
           ...
2235     14.032077
2236     89.389730
2237     57.610957
2238    255.000000
2239     13.945000
Name: total_price, Length: 239, dtype: float64

In [13]:
order.groupby('city')['total_price'].mean()

city
#07-01 FONTANA HGTS     20.000000
#36 NYE                 14.975000
.EASTHAM                34.100000
0201 OSLO               32.000000
05446-030               14.000000
                          ...
ZIONSDILLE              12.975000
ZIONSVILLE              39.143636
ZIONSVIOLE              67.500000
ZOLLIKERBERG           109.975000
ZURICH                  80.750000
Name: total_price, Length: 12824, dtype: float64

In [14]:
order.groupby('payment_type')['total_price'].mean()

payment_type
??     3.783291
AE    98.265967
DB    36.973761
MC    69.795414
OC    32.219117
VI    65.095214
Name: total_price, dtype: float64

In [15]:
order.groupby('campaign_id')['total_price'].std()

campaign_id
2001      0.000000
2002    113.462786
2003     13.052963
2004      1.703183
2005    145.842314
           ...
2235     16.650776
2236    219.812730
2237    362.825503
2238           NaN
2239      8.538780
Name: total_price, Length: 239, dtype: float64

In [16]:
order.groupby('city')['total_price'].std()

city
#07-01 FONTANA HGTS           NaN
#36 NYE                 21.177848
.EASTHAM                12.940054
0201 OSLO                     NaN
05446-030                     NaN
                          ...
ZIONSDILLE              18.349421
ZIONSVILLE              39.850142
ZIONSVIOLE                    NaN
ZOLLIKERBERG           120.243508
ZURICH                  71.516615
Name: total_price, Length: 12824, dtype: float64

In [17]:
order.groupby('payment_type')['total_price'].std()

payment_type
??     24.770624
AE    250.719743
DB    167.792583
MC    162.673419
OC     93.343014
VI    151.662093
Name: total_price, dtype: float64